-- ============================================================
-- Tracker Nawyków — schemat bazy danych
-- ============================================================
-- Wykonaj ten plik w panelu Supabase: SQL Editor → New query → Run
-- Tworzy tabele, ograniczenia oraz polityki Row Level Security.
-- ============================================================


-- ------------------------------------------------------------
-- Tabela: habits
-- Przechowuje nawyki. Każdy nawyk należy do jednego użytkownika.
-- ------------------------------------------------------------
create table habits (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  name        text        not null,
  user_id     uuid        not null references auth.users (id) on delete cascade
);


-- ------------------------------------------------------------
-- Tabela: completions
-- Jeden wiersz = jeden dzień, w którym dany nawyk został wykonany.
-- Historia odhaczeń jest źródłem prawdy dla liczenia serii (streak).
-- ------------------------------------------------------------
create table completions (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  habit_id    bigint      not null references habits (id) on delete cascade,
  date        date        not null
);

-- Blokuje dwukrotne odhaczenie tego samego nawyku w ciągu jednego dnia.
alter table completions
  add constraint unique_habit_date unique (habit_id, date);


-- ============================================================
-- Row Level Security
-- ============================================================
-- Izolacja danych wymuszona na poziomie bazy, nie tylko aplikacji.
-- Bez tych polityk tabele są całkowicie niedostępne.
-- ============================================================

alter table habits      enable row level security;
alter table completions enable row level security;


-- ------------------------------------------------------------
-- Polityki: habits
-- Użytkownik operuje wyłącznie na wierszach, których jest właścicielem.
-- ------------------------------------------------------------
create policy "Users can view own habits"
  on habits for select
  using (auth.uid() = user_id);

create policy "Users can insert own habits"
  on habits for insert
  with check (auth.uid() = user_id);

create policy "Users can update own habits"
  on habits for update
  using (auth.uid() = user_id);

create policy "Users can delete own habits"
  on habits for delete
  using (auth.uid() = user_id);


-- ------------------------------------------------------------
-- Polityki: completions
-- Tabela nie ma własnej kolumny user_id — właściciel ustalany jest
-- pośrednio, przez nawyk wskazywany przez habit_id.
-- ------------------------------------------------------------
create policy "Users can view own completions"
  on completions for select
  using (
    habit_id in (select id from habits where user_id = auth.uid())
  );

create policy "Users can insert own completions"
  on completions for insert
  with check (
    habit_id in (select id from habits where user_id = auth.uid())
  );

create policy "Users can delete own completions"
  on completions for delete
  using (
    habit_id in (select id from habits where user_id = auth.uid())
  );